dist: xenial
language: python

env:
  global:
    - ENV_FOR_DYNACONF=travis
    - PYTHONPATH=src/

install:
  - pip install pipenv --upgrade
  - make venv

script:
  - make test

after_success:
  - codecov

cache: pip

jobs:
  include:
    - stage: test
      python: '3.8'
    - stage: test
      python: '3.7'
