default:
  BELORUSNEFT_URL: "https://azs.belorusneft.by/sitebeloil/en/center/azs/center/fuel/price/index.html"
  BENZAK_API_TOKEN: null
  BENZAK_API_URL: "https://benzak.herokuapp.com/api/v1"
  DEBUG: false
  FULL_LOAD: false
  SENTRY_DSN: ""

development:
  BENZAK_API_URL: "http://localhost:8000/api/v1"
  DEBUG: true

testing:
  BELORUSNEFT_URL: "tests/belorusneft_prices.html"
  DEBUG: false

production:
  DEBUG: false
